### 1.1 
get http://localhost:3000/todos/?status=TO%20DO 

### 1.2
get http://localhost:3000/todos/?priority=HIGH

### 1.3
get http://localhost:3000/todos/?status=IN%PROGRESS&priority=HIGH 

### 1.4
get http://localhost:3000/todos/?search_q=Play

### 2
get http://localhost:3000/todos/2/

### 3
post http://localhost:3000/todos/ 
Content-Type: application/json 

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

### 4.1
put http://localhost:3000/todos/3/
Content-Type: application/json

{
      "status": "DONE"
    }

### 4.2

put http://localhost:3000/todos/3/
Content-Type: application/json

{
      "priority": "HIGH"
    }

### 4.3 

put http://localhost:3000/todos/3/
Content-Type: application/json

{
      "todo": "Some task"
    }

### 5 
delete http://localhost:3000/todos/3/
Content-Type: application/json 




